### ISSUE TITLE
Use epiphany-browser?

### ISSUE THREAD

**Issue by elalemanyo** [basdegroot/raspberry-pi-kiosk#1]
Hi,
The webpage that I need to show have some animations, I thought that maybe with Epiphany will run smoothly. What do you think?

Thanks

**Comment by basdegroot** [comment]
I have no experience with Epiphany.  This webpage says it runs better;
http://www.raspi.today/5-things-you-need-to-know-about-the-raspberry-pis-epiphany-web-browser/

Try it! and let me know how it runs!

**Comment by elalemanyo** [comment]
https://github.com/elalemanyo/raspberry-pi-kiosk-screen#epiphany-browser

**Comment by basdegroot** [comment]
nice job! :+1:
