### ISSUE TITLE
no 'Chromium' packages available for ARMhf

### ISSUE THREAD

**Issue by export-mike** [basdegroot/raspberry-pi-kiosk#2]
see:
https://www.raspberrypi.org/forums/viewtopic.php?t=109309&p=751381

**Comment by basdegroot** [comment]
You can try Epiphany Browser

https://github.com/elalemanyo/raspberry-pi-kiosk-screen#epiphany-browser

**Comment by export-mike** [comment]
Thanks!

**Comment by markstos** [comment]
It would be helpful to mention instructions directly for ARMhf in the README. I just got a Raspberry Pi 3, and it identifies the architecture as "armv7l". There's no `chromium` package for it either.

**Comment by basdegroot** [comment]
I have added the mention to the README. Thanks
