### ISSUE TITLE
Raspberry Jessie with Pixel (2016-09-23) autostart file not working

### ISSUE THREAD

**Issue by rgardner** [basdegroot/raspberry-pi-kiosk#4]
Modifying `/etc/xdg/lxsession/LXDE-pi/autostart` does not seem to work; chromium was not started after boot (it's actually `chromium-browser` in this release).

I got it working by modifying `~/.config/lxsession/LXDE-pi/autostart` instead.

**Comment by basdegroot** [comment]
I just pushed a commit which is based on Raspbian Jessie with Pixel

**Comment by paulooliveira** [comment]
Tnx, this helped me!
